apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-api
  namespace: prod
spec:
  rules:
  - host: customer.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: customer-api
            port:
              number: 80
